import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function seedMaterials() {
  console.log('🎨 Seeding materials for modeling company...');

  // Create suppliers first
  console.log('🏭 Creating suppliers...');
  const suppliers = await Promise.all([
    prisma.supplier.upsert({
      where: { code: 'SUP-RESINE' },
      update: {},
      create: {
        code: 'SUP-RESINE',
        businessName: 'Resine Italia Srl',
        email: 'ordini@resineitalia.it',
        phone: '+39 02 1234567',
        taxId: 'IT01234567890',
        address: {
          street: 'Via Industriale 45',
          city: 'Milano',
          province: 'MI',
          zip: '20100',
          country: 'IT',
        },
        paymentTerms: 30,
      },
    }),
    prisma.supplier.upsert({
      where: { code: 'SUP-SILICONI' },
      update: {},
      create: {
        code: 'SUP-SILICONI',
        businessName: 'SilMold Europe',
        email: 'sales@silmold.eu',
        phone: '+39 051 9876543',
        taxId: 'IT09876543210',
        address: {
          street: 'Via della Gomma 12',
          city: 'Bologna',
          province: 'BO',
          zip: '40100',
          country: 'IT',
        },
        paymentTerms: 45,
      },
    }),
    prisma.supplier.upsert({
      where: { code: 'SUP-COLORI' },
      update: {},
      create: {
        code: 'SUP-COLORI',
        businessName: 'Vallejo Colors Distributor',
        email: 'italia@vallejo.com',
        phone: '+39 06 5551234',
        taxId: 'IT11223344556',
        address: {
          street: 'Via dei Colori 88',
          city: 'Roma',
          province: 'RM',
          zip: '00100',
          country: 'IT',
        },
        paymentTerms: 30,
      },
    }),
    prisma.supplier.upsert({
      where: { code: 'SUP-3DPRINT' },
      update: {},
      create: {
        code: 'SUP-3DPRINT',
        businessName: '3D Print Supply',
        email: 'info@3dprintsupply.it',
        phone: '+39 011 7778899',
        taxId: 'IT55667788990',
        address: {
          street: 'Corso Tecnologia 200',
          city: 'Torino',
          province: 'TO',
          zip: '10100',
          country: 'IT',
        },
        paymentTerms: 15,
      },
    }),
    prisma.supplier.upsert({
      where: { code: 'SUP-IMBALL' },
      update: {},
      create: {
        code: 'SUP-IMBALL',
        businessName: 'PackModel Srl',
        email: 'ordini@packmodel.it',
        phone: '+39 049 3332211',
        taxId: 'IT99887766554',
        address: {
          street: 'Via Imballaggi 5',
          city: 'Padova',
          province: 'PD',
          zip: '35100',
          country: 'IT',
        },
        paymentTerms: 60,
      },
    }),
  ]);

  const [supResine, supSiliconi, supColori, sup3DPrint, supImball] = suppliers;
  console.log(`✅ Created ${suppliers.length} suppliers`);

  // Materials data for modeling company
  const materialsData = [
    // === RESINE ===
    {
      sku: 'MAT-RES-PU-A',
      name: 'Resina Poliuretanica Componente A',
      description: 'Componente A (poliolo) per resina poliuretanica da colata. Rapporto 1:1 con componente B.',
      unit: 'kg',
      cost: 12.50,
      minStock: 20,
      currentStock: 45,
      reorderPoint: 25,
      reorderQuantity: 50,
      leadTimeDays: 5,
      category: 'Resine',
      isConsumable: false,
      supplierId: supResine.id,
    },
    {
      sku: 'MAT-RES-PU-B',
      name: 'Resina Poliuretanica Componente B',
      description: 'Componente B (isocianato) per resina poliuretanica da colata. Rapporto 1:1 con componente A.',
      unit: 'kg',
      cost: 14.80,
      minStock: 20,
      currentStock: 42,
      reorderPoint: 25,
      reorderQuantity: 50,
      leadTimeDays: 5,
      category: 'Resine',
      isConsumable: false,
      supplierId: supResine.id,
    },
    {
      sku: 'MAT-RES-EP-A',
      name: 'Resina Epossidica Trasparente Comp. A',
      description: 'Resina epossidica cristallina per inclusioni e basi trasparenti. Rapporto 2:1.',
      unit: 'kg',
      cost: 28.00,
      minStock: 10,
      currentStock: 18,
      reorderPoint: 12,
      reorderQuantity: 20,
      leadTimeDays: 7,
      category: 'Resine',
      isConsumable: false,
      supplierId: supResine.id,
    },
    {
      sku: 'MAT-RES-EP-B',
      name: 'Resina Epossidica Trasparente Comp. B',
      description: 'Indurente per resina epossidica trasparente. Rapporto 2:1 con componente A.',
      unit: 'kg',
      cost: 32.00,
      minStock: 5,
      currentStock: 9,
      reorderPoint: 6,
      reorderQuantity: 10,
      leadTimeDays: 7,
      category: 'Resine',
      isConsumable: false,
      supplierId: supResine.id,
    },
    {
      sku: 'MAT-RES-UV',
      name: 'Resina UV per Stampa 3D - Grigia',
      description: 'Resina fotopolimerica standard per stampanti LCD/DLP. Colore grigio.',
      unit: 'l',
      cost: 35.00,
      minStock: 10,
      currentStock: 24,
      reorderPoint: 12,
      reorderQuantity: 20,
      leadTimeDays: 3,
      category: 'Resine 3D',
      isConsumable: false,
      supplierId: sup3DPrint.id,
    },
    {
      sku: 'MAT-RES-UV-W',
      name: 'Resina UV per Stampa 3D - Bianca',
      description: 'Resina fotopolimerica per dettagli fini. Colore bianco.',
      unit: 'l',
      cost: 38.00,
      minStock: 5,
      currentStock: 12,
      reorderPoint: 6,
      reorderQuantity: 10,
      leadTimeDays: 3,
      category: 'Resine 3D',
      isConsumable: false,
      supplierId: sup3DPrint.id,
    },
    {
      sku: 'MAT-RES-ABS',
      name: 'Resina ABS-Like per Stampa 3D',
      description: 'Resina ad alta resistenza meccanica, simil-ABS.',
      unit: 'l',
      cost: 45.00,
      minStock: 5,
      currentStock: 8,
      reorderPoint: 6,
      reorderQuantity: 10,
      leadTimeDays: 5,
      category: 'Resine 3D',
      isConsumable: false,
      supplierId: sup3DPrint.id,
    },

    // === SILICONI ===
    {
      sku: 'MAT-SIL-25A',
      name: 'Silicone per Stampi Shore 25',
      description: 'Silicone bicomponente morbido per stampi con sottosquadri. Shore A 25.',
      unit: 'kg',
      cost: 22.00,
      minStock: 15,
      currentStock: 28,
      reorderPoint: 18,
      reorderQuantity: 30,
      leadTimeDays: 5,
      category: 'Siliconi',
      isConsumable: false,
      supplierId: supSiliconi.id,
    },
    {
      sku: 'MAT-SIL-40A',
      name: 'Silicone per Stampi Shore 40',
      description: 'Silicone bicomponente medio per stampi standard. Shore A 40.',
      unit: 'kg',
      cost: 20.00,
      minStock: 20,
      currentStock: 35,
      reorderPoint: 22,
      reorderQuantity: 40,
      leadTimeDays: 5,
      category: 'Siliconi',
      isConsumable: false,
      supplierId: supSiliconi.id,
    },
    {
      sku: 'MAT-SIL-CAT',
      name: 'Catalizzatore Silicone Standard',
      description: 'Catalizzatore per siliconi bicomponenti. Rapporto 10:1.',
      unit: 'kg',
      cost: 35.00,
      minStock: 5,
      currentStock: 8,
      reorderPoint: 6,
      reorderQuantity: 10,
      leadTimeDays: 5,
      category: 'Siliconi',
      isConsumable: false,
      supplierId: supSiliconi.id,
    },
    {
      sku: 'MAT-SIL-TIXO',
      name: 'Addensante Tixotropico per Silicone',
      description: 'Addensante per applicazione a pennello del silicone.',
      unit: 'kg',
      cost: 18.00,
      minStock: 2,
      currentStock: 5,
      reorderPoint: 3,
      reorderQuantity: 5,
      leadTimeDays: 7,
      category: 'Siliconi',
      isConsumable: false,
      supplierId: supSiliconi.id,
    },

    // === COLORI E VERNICI ===
    {
      sku: 'MAT-COL-PRIMER-GR',
      name: 'Primer Grigio Spray 400ml',
      description: 'Primer aggrappante universale grigio per resine e plastica.',
      unit: 'pz',
      cost: 8.50,
      minStock: 30,
      currentStock: 65,
      reorderPoint: 35,
      reorderQuantity: 50,
      leadTimeDays: 3,
      category: 'Primer',
      isConsumable: true,
      supplierId: supColori.id,
    },
    {
      sku: 'MAT-COL-PRIMER-WH',
      name: 'Primer Bianco Spray 400ml',
      description: 'Primer aggrappante universale bianco per resine e plastica.',
      unit: 'pz',
      cost: 8.50,
      minStock: 20,
      currentStock: 45,
      reorderPoint: 25,
      reorderQuantity: 40,
      leadTimeDays: 3,
      category: 'Primer',
      isConsumable: true,
      supplierId: supColori.id,
    },
    {
      sku: 'MAT-COL-PRIMER-BK',
      name: 'Primer Nero Spray 400ml',
      description: 'Primer aggrappante universale nero per resine e plastica.',
      unit: 'pz',
      cost: 8.50,
      minStock: 20,
      currentStock: 38,
      reorderPoint: 25,
      reorderQuantity: 40,
      leadTimeDays: 3,
      category: 'Primer',
      isConsumable: true,
      supplierId: supColori.id,
    },
    {
      sku: 'MAT-COL-ACR-SET',
      name: 'Set Colori Acrilici Base 16 pz',
      description: 'Set colori acrilici Vallejo Model Color - colori base 17ml x16.',
      unit: 'set',
      cost: 42.00,
      minStock: 5,
      currentStock: 12,
      reorderPoint: 6,
      reorderQuantity: 10,
      leadTimeDays: 5,
      category: 'Colori Acrilici',
      isConsumable: true,
      supplierId: supColori.id,
    },
    {
      sku: 'MAT-COL-ACR-WHT',
      name: 'Acrilico Bianco Puro 17ml',
      description: 'Vallejo Model Color 001 - Bianco Puro.',
      unit: 'pz',
      cost: 3.20,
      minStock: 20,
      currentStock: 48,
      reorderPoint: 25,
      reorderQuantity: 30,
      leadTimeDays: 3,
      category: 'Colori Acrilici',
      isConsumable: true,
      supplierId: supColori.id,
    },
    {
      sku: 'MAT-COL-ACR-BLK',
      name: 'Acrilico Nero Puro 17ml',
      description: 'Vallejo Model Color 169 - Nero Puro.',
      unit: 'pz',
      cost: 3.20,
      minStock: 20,
      currentStock: 42,
      reorderPoint: 25,
      reorderQuantity: 30,
      leadTimeDays: 3,
      category: 'Colori Acrilici',
      isConsumable: true,
      supplierId: supColori.id,
    },
    {
      sku: 'MAT-COL-METAL-GLD',
      name: 'Acrilico Metallico Oro 17ml',
      description: 'Vallejo Model Color - Oro metallico.',
      unit: 'pz',
      cost: 3.80,
      minStock: 15,
      currentStock: 32,
      reorderPoint: 18,
      reorderQuantity: 25,
      leadTimeDays: 3,
      category: 'Colori Metallici',
      isConsumable: true,
      supplierId: supColori.id,
    },
    {
      sku: 'MAT-COL-METAL-SLV',
      name: 'Acrilico Metallico Argento 17ml',
      description: 'Vallejo Model Color - Argento metallico.',
      unit: 'pz',
      cost: 3.80,
      minStock: 15,
      currentStock: 35,
      reorderPoint: 18,
      reorderQuantity: 25,
      leadTimeDays: 3,
      category: 'Colori Metallici',
      isConsumable: true,
      supplierId: supColori.id,
    },
    {
      sku: 'MAT-COL-WASH-BRN',
      name: 'Wash Marrone 17ml',
      description: 'Inchiostro per ombreggiature e invecchiamento - marrone.',
      unit: 'pz',
      cost: 3.50,
      minStock: 10,
      currentStock: 25,
      reorderPoint: 12,
      reorderQuantity: 20,
      leadTimeDays: 3,
      category: 'Wash e Inchiostri',
      isConsumable: true,
      supplierId: supColori.id,
    },
    {
      sku: 'MAT-COL-WASH-BLK',
      name: 'Wash Nero 17ml',
      description: 'Inchiostro per ombreggiature e invecchiamento - nero.',
      unit: 'pz',
      cost: 3.50,
      minStock: 10,
      currentStock: 28,
      reorderPoint: 12,
      reorderQuantity: 20,
      leadTimeDays: 3,
      category: 'Wash e Inchiostri',
      isConsumable: true,
      supplierId: supColori.id,
    },
    {
      sku: 'MAT-COL-VERN-OPA',
      name: 'Vernice Finale Opaca Spray 400ml',
      description: 'Vernice protettiva finale opaca per modelli.',
      unit: 'pz',
      cost: 9.50,
      minStock: 15,
      currentStock: 35,
      reorderPoint: 18,
      reorderQuantity: 30,
      leadTimeDays: 3,
      category: 'Vernici Finali',
      isConsumable: true,
      supplierId: supColori.id,
    },
    {
      sku: 'MAT-COL-VERN-SAT',
      name: 'Vernice Finale Satinata Spray 400ml',
      description: 'Vernice protettiva finale satinata per modelli.',
      unit: 'pz',
      cost: 9.50,
      minStock: 10,
      currentStock: 22,
      reorderPoint: 12,
      reorderQuantity: 20,
      leadTimeDays: 3,
      category: 'Vernici Finali',
      isConsumable: true,
      supplierId: supColori.id,
    },
    {
      sku: 'MAT-COL-VERN-LUC',
      name: 'Vernice Finale Lucida Spray 400ml',
      description: 'Vernice protettiva finale lucida per modelli.',
      unit: 'pz',
      cost: 9.50,
      minStock: 10,
      currentStock: 18,
      reorderPoint: 12,
      reorderQuantity: 20,
      leadTimeDays: 3,
      category: 'Vernici Finali',
      isConsumable: true,
      supplierId: supColori.id,
    },

    // === PIGMENTI E ADDITIVI ===
    {
      sku: 'MAT-PIG-BLK',
      name: 'Pigmento Nero in Polvere 100g',
      description: 'Pigmento nero per colorazione resine e weathering.',
      unit: 'pz',
      cost: 8.00,
      minStock: 10,
      currentStock: 18,
      reorderPoint: 12,
      reorderQuantity: 15,
      leadTimeDays: 5,
      category: 'Pigmenti',
      isConsumable: true,
      supplierId: supResine.id,
    },
    {
      sku: 'MAT-PIG-WHT',
      name: 'Pigmento Bianco in Polvere 100g',
      description: 'Pigmento bianco per colorazione resine.',
      unit: 'pz',
      cost: 7.50,
      minStock: 10,
      currentStock: 15,
      reorderPoint: 12,
      reorderQuantity: 15,
      leadTimeDays: 5,
      category: 'Pigmenti',
      isConsumable: true,
      supplierId: supResine.id,
    },
    {
      sku: 'MAT-ADD-DEGAS',
      name: 'Degasante per Resine 250ml',
      description: 'Additivo per eliminare bolle d\'aria nelle resine.',
      unit: 'pz',
      cost: 15.00,
      minStock: 5,
      currentStock: 12,
      reorderPoint: 6,
      reorderQuantity: 10,
      leadTimeDays: 7,
      category: 'Additivi',
      isConsumable: true,
      supplierId: supResine.id,
    },
    {
      sku: 'MAT-ADD-DISTAC',
      name: 'Distaccante Spray 500ml',
      description: 'Distaccante siliconico per stampi.',
      unit: 'pz',
      cost: 12.00,
      minStock: 10,
      currentStock: 25,
      reorderPoint: 12,
      reorderQuantity: 20,
      leadTimeDays: 5,
      category: 'Additivi',
      isConsumable: true,
      supplierId: supSiliconi.id,
    },

    // === STUCCHI E MATERIALI MODELLAZIONE ===
    {
      sku: 'MAT-STU-EPOX',
      name: 'Stucco Epossidico Bicomponente 200g',
      description: 'Stucco epossidico per scultura e riparazioni.',
      unit: 'pz',
      cost: 14.00,
      minStock: 15,
      currentStock: 28,
      reorderPoint: 18,
      reorderQuantity: 25,
      leadTimeDays: 5,
      category: 'Stucchi',
      isConsumable: true,
      supplierId: supResine.id,
    },
    {
      sku: 'MAT-STU-POLY',
      name: 'Stucco Poliestere 500g',
      description: 'Stucco poliestere per carrozzeria e grandi riempimenti.',
      unit: 'pz',
      cost: 8.50,
      minStock: 10,
      currentStock: 22,
      reorderPoint: 12,
      reorderQuantity: 20,
      leadTimeDays: 5,
      category: 'Stucchi',
      isConsumable: true,
      supplierId: supResine.id,
    },
    {
      sku: 'MAT-MILLIPUT-STD',
      name: 'Milliput Standard 113g',
      description: 'Stucco epossidico Milliput giallo-grigio per scultura.',
      unit: 'pz',
      cost: 7.50,
      minStock: 20,
      currentStock: 45,
      reorderPoint: 25,
      reorderQuantity: 30,
      leadTimeDays: 3,
      category: 'Stucchi',
      isConsumable: true,
      supplierId: supColori.id,
    },
    {
      sku: 'MAT-MILLIPUT-SUP',
      name: 'Milliput Superfine White 113g',
      description: 'Stucco epossidico Milliput bianco ultrafine.',
      unit: 'pz',
      cost: 8.50,
      minStock: 15,
      currentStock: 32,
      reorderPoint: 18,
      reorderQuantity: 25,
      leadTimeDays: 3,
      category: 'Stucchi',
      isConsumable: true,
      supplierId: supColori.id,
    },
    {
      sku: 'MAT-GREENSTUFF',
      name: 'Green Stuff 36"',
      description: 'Stucco epossidico verde/blu per scultura dettagli.',
      unit: 'pz',
      cost: 12.00,
      minStock: 10,
      currentStock: 28,
      reorderPoint: 12,
      reorderQuantity: 20,
      leadTimeDays: 5,
      category: 'Stucchi',
      isConsumable: true,
      supplierId: supColori.id,
    },

    // === COLLE E ADESIVI ===
    {
      sku: 'MAT-COLLA-CIANO',
      name: 'Colla Cianoacrilica 20g',
      description: 'Super colla istantanea per plastica, resina e metallo.',
      unit: 'pz',
      cost: 4.50,
      minStock: 30,
      currentStock: 75,
      reorderPoint: 35,
      reorderQuantity: 50,
      leadTimeDays: 3,
      category: 'Colle',
      isConsumable: true,
      supplierId: supColori.id,
    },
    {
      sku: 'MAT-COLLA-CIANO-GEL',
      name: 'Colla Cianoacrilica Gel 20g',
      description: 'Super colla gel per superfici verticali.',
      unit: 'pz',
      cost: 5.50,
      minStock: 20,
      currentStock: 42,
      reorderPoint: 25,
      reorderQuantity: 35,
      leadTimeDays: 3,
      category: 'Colle',
      isConsumable: true,
      supplierId: supColori.id,
    },
    {
      sku: 'MAT-COLLA-PVA',
      name: 'Colla Vinilica PVA 250ml',
      description: 'Colla bianca per basi e scenografie.',
      unit: 'pz',
      cost: 3.50,
      minStock: 15,
      currentStock: 35,
      reorderPoint: 18,
      reorderQuantity: 25,
      leadTimeDays: 3,
      category: 'Colle',
      isConsumable: true,
      supplierId: supColori.id,
    },
    {
      sku: 'MAT-COLLA-EPOX',
      name: 'Colla Epossidica Bicomponente 28g',
      description: 'Adesivo strutturale per giunzioni resistenti.',
      unit: 'pz',
      cost: 6.00,
      minStock: 15,
      currentStock: 28,
      reorderPoint: 18,
      reorderQuantity: 25,
      leadTimeDays: 5,
      category: 'Colle',
      isConsumable: true,
      supplierId: supResine.id,
    },
    {
      sku: 'MAT-ATTIV-CIANO',
      name: 'Attivatore per Cianoacrilica 200ml',
      description: 'Accelerante spray per colla cianoacrilica.',
      unit: 'pz',
      cost: 8.00,
      minStock: 10,
      currentStock: 22,
      reorderPoint: 12,
      reorderQuantity: 15,
      leadTimeDays: 3,
      category: 'Colle',
      isConsumable: true,
      supplierId: supColori.id,
    },

    // === FILAMENTI 3D ===
    {
      sku: 'MAT-FIL-PLA-WH',
      name: 'Filamento PLA 1.75mm Bianco 1kg',
      description: 'Filamento PLA per stampa FDM, colore bianco.',
      unit: 'pz',
      cost: 22.00,
      minStock: 10,
      currentStock: 18,
      reorderPoint: 12,
      reorderQuantity: 15,
      leadTimeDays: 3,
      category: 'Filamenti 3D',
      isConsumable: false,
      supplierId: sup3DPrint.id,
    },
    {
      sku: 'MAT-FIL-PLA-BK',
      name: 'Filamento PLA 1.75mm Nero 1kg',
      description: 'Filamento PLA per stampa FDM, colore nero.',
      unit: 'pz',
      cost: 22.00,
      minStock: 10,
      currentStock: 15,
      reorderPoint: 12,
      reorderQuantity: 15,
      leadTimeDays: 3,
      category: 'Filamenti 3D',
      isConsumable: false,
      supplierId: sup3DPrint.id,
    },
    {
      sku: 'MAT-FIL-ABS-GR',
      name: 'Filamento ABS 1.75mm Grigio 1kg',
      description: 'Filamento ABS per stampa FDM, colore grigio.',
      unit: 'pz',
      cost: 25.00,
      minStock: 5,
      currentStock: 10,
      reorderPoint: 6,
      reorderQuantity: 10,
      leadTimeDays: 3,
      category: 'Filamenti 3D',
      isConsumable: false,
      supplierId: sup3DPrint.id,
    },

    // === CONSUMABILI E UTENSILI ===
    {
      sku: 'MAT-CONS-GUANTI-M',
      name: 'Guanti Nitrile Taglia M - Box 100pz',
      description: 'Guanti monouso in nitrile per lavorazione resine.',
      unit: 'box',
      cost: 12.00,
      minStock: 10,
      currentStock: 25,
      reorderPoint: 12,
      reorderQuantity: 20,
      leadTimeDays: 3,
      category: 'Consumabili',
      isConsumable: true,
      supplierId: supResine.id,
    },
    {
      sku: 'MAT-CONS-GUANTI-L',
      name: 'Guanti Nitrile Taglia L - Box 100pz',
      description: 'Guanti monouso in nitrile per lavorazione resine.',
      unit: 'box',
      cost: 12.00,
      minStock: 10,
      currentStock: 22,
      reorderPoint: 12,
      reorderQuantity: 20,
      leadTimeDays: 3,
      category: 'Consumabili',
      isConsumable: true,
      supplierId: supResine.id,
    },
    {
      sku: 'MAT-CONS-BICCH',
      name: 'Bicchieri Graduati 100ml - 50pz',
      description: 'Bicchieri in plastica graduati per miscelazione.',
      unit: 'conf',
      cost: 8.00,
      minStock: 5,
      currentStock: 15,
      reorderPoint: 6,
      reorderQuantity: 10,
      leadTimeDays: 3,
      category: 'Consumabili',
      isConsumable: true,
      supplierId: supResine.id,
    },
    {
      sku: 'MAT-CONS-SPATOLE',
      name: 'Spatole in Legno - 100pz',
      description: 'Spatole monouso per miscelazione resine e siliconi.',
      unit: 'conf',
      cost: 5.00,
      minStock: 10,
      currentStock: 28,
      reorderPoint: 12,
      reorderQuantity: 20,
      leadTimeDays: 3,
      category: 'Consumabili',
      isConsumable: true,
      supplierId: supResine.id,
    },
    {
      sku: 'MAT-CONS-CARTA-ABR',
      name: 'Set Carta Abrasiva Assortita',
      description: 'Set carte abrasive grana 400-600-800-1000-1200-2000.',
      unit: 'set',
      cost: 6.50,
      minStock: 15,
      currentStock: 35,
      reorderPoint: 18,
      reorderQuantity: 25,
      leadTimeDays: 3,
      category: 'Consumabili',
      isConsumable: true,
      supplierId: supColori.id,
    },
    {
      sku: 'MAT-CONS-PENNELLI',
      name: 'Set Pennelli Sintetici 10pz',
      description: 'Set pennelli a punta fine per pittura dettagli.',
      unit: 'set',
      cost: 15.00,
      minStock: 10,
      currentStock: 22,
      reorderPoint: 12,
      reorderQuantity: 15,
      leadTimeDays: 3,
      category: 'Utensili',
      isConsumable: true,
      supplierId: supColori.id,
    },
    {
      sku: 'MAT-CONS-LAME',
      name: 'Lame di Ricambio X-Acto #11 - 100pz',
      description: 'Lame di ricambio per cutter di precisione.',
      unit: 'conf',
      cost: 18.00,
      minStock: 5,
      currentStock: 12,
      reorderPoint: 6,
      reorderQuantity: 10,
      leadTimeDays: 5,
      category: 'Utensili',
      isConsumable: true,
      supplierId: supColori.id,
    },

    // === IMBALLAGGIO ===
    {
      sku: 'MAT-IMB-SCATOLA-S',
      name: 'Scatola Cartone 15x15x10cm',
      description: 'Scatola in cartone per spedizione modelli piccoli.',
      unit: 'pz',
      cost: 0.85,
      minStock: 100,
      currentStock: 280,
      reorderPoint: 120,
      reorderQuantity: 200,
      leadTimeDays: 5,
      category: 'Imballaggio',
      isConsumable: true,
      supplierId: supImball.id,
    },
    {
      sku: 'MAT-IMB-SCATOLA-M',
      name: 'Scatola Cartone 25x20x15cm',
      description: 'Scatola in cartone per spedizione modelli medi.',
      unit: 'pz',
      cost: 1.20,
      minStock: 80,
      currentStock: 195,
      reorderPoint: 100,
      reorderQuantity: 150,
      leadTimeDays: 5,
      category: 'Imballaggio',
      isConsumable: true,
      supplierId: supImball.id,
    },
    {
      sku: 'MAT-IMB-SCATOLA-L',
      name: 'Scatola Cartone 35x30x25cm',
      description: 'Scatola in cartone per spedizione modelli grandi.',
      unit: 'pz',
      cost: 1.80,
      minStock: 50,
      currentStock: 125,
      reorderPoint: 60,
      reorderQuantity: 100,
      leadTimeDays: 5,
      category: 'Imballaggio',
      isConsumable: true,
      supplierId: supImball.id,
    },
    {
      sku: 'MAT-IMB-PLURIBALL',
      name: 'Pluriball Rotolo 50cm x 100m',
      description: 'Pluriball per protezione modelli.',
      unit: 'pz',
      cost: 25.00,
      minStock: 5,
      currentStock: 12,
      reorderPoint: 6,
      reorderQuantity: 10,
      leadTimeDays: 5,
      category: 'Imballaggio',
      isConsumable: true,
      supplierId: supImball.id,
    },
    {
      sku: 'MAT-IMB-CHIPS',
      name: 'Chips Polistirolo Sacco 200L',
      description: 'Chips di riempimento per protezione spedizioni.',
      unit: 'sacco',
      cost: 18.00,
      minStock: 5,
      currentStock: 10,
      reorderPoint: 6,
      reorderQuantity: 10,
      leadTimeDays: 5,
      category: 'Imballaggio',
      isConsumable: true,
      supplierId: supImball.id,
    },
    {
      sku: 'MAT-IMB-NASTRO',
      name: 'Nastro Adesivo da Imballo 50mm - 6pz',
      description: 'Nastro adesivo marrone per chiusura scatole.',
      unit: 'conf',
      cost: 8.00,
      minStock: 10,
      currentStock: 25,
      reorderPoint: 12,
      reorderQuantity: 20,
      leadTimeDays: 3,
      category: 'Imballaggio',
      isConsumable: true,
      supplierId: supImball.id,
    },
  ];

  // Create materials
  console.log('🎨 Creating materials...');
  let created = 0;
  let updated = 0;

  for (const material of materialsData) {
    const result = await prisma.material.upsert({
      where: { sku: material.sku },
      update: {
        name: material.name,
        description: material.description,
        unit: material.unit,
        cost: material.cost,
        minStock: material.minStock,
        currentStock: material.currentStock,
        reorderPoint: material.reorderPoint,
        reorderQuantity: material.reorderQuantity,
        leadTimeDays: material.leadTimeDays,
        category: material.category,
        isConsumable: material.isConsumable,
        supplierId: material.supplierId,
      },
      create: material,
    });

    // Check if it was created or updated
    if (result.createdAt.getTime() === result.updatedAt.getTime()) {
      created++;
    } else {
      updated++;
    }
  }

  console.log(`✅ Materials: ${created} created, ${updated} updated`);

  // Summary
  const categories = await prisma.material.groupBy({
    by: ['category'],
    _count: { id: true },
  });

  console.log('\n🎉 Materials seeding completed!');
  console.log('\n📊 Summary by category:');
  for (const cat of categories) {
    console.log(`  - ${cat.category || 'Uncategorized'}: ${cat._count.id}`);
  }

  const totalValue = await prisma.material.aggregate({
    _sum: {
      currentStock: true,
    },
  });

  const materialsCount = await prisma.material.count();
  console.log(`\n📦 Total materials: ${materialsCount}`);
  console.log(`🏭 Total suppliers: ${suppliers.length}`);
}

seedMaterials()
  .catch((e) => {
    console.error('❌ Error seeding materials:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
